generic:
  database: jade.db
  chunkCost: 20
  gameworlds:
    - world
gamerules:
  preventCoralFading: true
  enablePlayerGraves: true
  enableSpeedRoads: true
  sayRandomAdvice: true
  doMonsterGriefing: false
roads:
  - ANY;PACKED_MUD;GRAVEL;2